### ISSUE TITLE
Notifying user if its not possible to display all inputted words

### ISSUE THREAD

**Issue by helenyueyu** [Ruben9922/wordsearch#7]
Hi! So I stumbled across your app and it is pretty awesome.

One thing I noticed is that the app doesn't inform you if not all words you entered can be displayed in the word search itself. Just as an example - I entered 12 sample long words on a 15 x 15 grid, but only 8 of them were displayed. Actually, I think 2 more words can be displayed (one on the bottom row and the other on the most right column), but for some reason this space isn't being utilized (not sure about the algorithm, as I haven't taken a look at the code). 

Anyways, I think it would be a good idea to send an alert message, or a modal dialog of some sort notifying the user of something along the lines of "Total inputted words exceeded capacity. Only 8/12 words shown". 

<img width="1073" alt="screen shot 2019-01-26 at 4 41 02 pm" src="https://user-images.githubusercontent.com/42653937/51794531-97a63880-2189-11e9-8e44-aa35d5d8d127.png">

Also, have you thought about transforming this app into a dynamic online game? Maybe you could use a dictionary API like Wordnik to generate a word bank that the user can then play (maybe tinker around with some libraries for dragging UI?).

**Comment by Ruben9922** [comment]
Hi, thanks! It's cool that you found it.

That's really weird. After trying it myself just now I got the same behaviour. I'll have a look at the code and try to figure it out. Apologies for only just getting back to you now and thanks for letting me know!

And yeah, that would be awesome. I'll add them to the to-do list :slightly_smiling_face:
